"""create user optional info table

Revision ID: ed1aabfc2cfc
Revises: f11e5adabcda
Create Date: 2026-05-13 23:33:09.676510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed1aabfc2cfc'
down_revision: Union[str, Sequence[str], None] = 'f11e5adabcda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_optional_info',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_description', sa.Text(), nullable=True),
    sa.Column('first_icon_color', sa.String(length=7), server_default='#000000', nullable=False),
    sa.Column('second_icon_color', sa.String(length=7), server_default='#000000', nullable=False),
    sa.Column('icon_id', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_optional_info')
    # ### end Alembic commands ###
